config/routes.rb
Project01::Application.routes.draw do

  resources :users do
    resources :profiles
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => 'sessions#new'

  match '/signup',  to: 'users#new'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 800 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_one :profile, dependent: :destroy
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  force_ssl
  include SessionsHelper

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :signed_in_user
	before_filter :set_user
  
  def new
  	@profile = Profile.new
  end

  def create
  	@profile = @user.build_profile(params[:profile])
  	if @profile.save
      flash[:success] = 'Profile was successfully created.'
      redirect_to :action => 'show', :id => @user.id
    else
      flash[:notice] = 'Error.  Something went wrong.'
      render "new"
    end
  end

	def show
		 @user = User.find(params[:user_id])
	end

	def edit
		@user = User.find(params[:id])
		@profile = @user.profile(params[:user_id])
	end

	def update
		@user = User.find(params[:id])
		@profile = @user.profile
		if @profile.update_attributes(params[:profile])
      flash[:success] = "Profile updated"
      redirect_to @profile
    else
      render 'edit'
    end
  end

  private

    def correct_user
      @profile = current_user.profile.find_by_id(params[:id])
      redirect_to root_path if @profile.nil?
    end

    def set_user
  @user = User.find(session[:user_id])
	end
end

__END__
  def index
	  @user = User.find(params[:user_id])
	  @profile = @user.profile(:order => "created_at DESC")
	end

	def show
	  @user = User.find(params[:user_id])
	  @profile = @user.profile.find(params[:id])
	end

	def new
	  @user = User.find(params[:user_id])
	  @profile = @user.profile.build
	end

	def edit
	  @user = User.find(params[:user_id])
	  @profile = @user.profile.find(params[:id])
	end

	def create
	  @user = User.find(params[:user_id])
	  @profile = @user.profile.build(params[:profile])
    if @profile.save
      flash[:notice] = 'Profile was successfully created.'
      redirect_to(@profile)
    else
      flash[:notice] = 'Error.  Something went wrong.'
      render :action => "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
    session[:user_id] = user.id
  	if user && user.authenticate(params[:password])
  	  sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
  	  render "new"
    end
  end

  def destroy
  	sign_out
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]

  def new
  	@user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show

  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      session[:user_id] = @user.id
  	  sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
  	else
  	  render "new"
  	end
  end

  private

    def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Customize Page", new_user_profile_path(current_user) %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project01</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/new.html.erb
<h1>Customize your Page</h1>


<div class="row">
  <div class="span6 offset3">

  	<%= form_for @profile, :url => { :action => "create" } do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_field :content %>  

      <%= f.submit "Customize", class: "btn btn-large btn-primary" %>
    <% end %>

<!--<%= form_tag do %>

  	<%= label_tag :title %>
  	<%= text_field_tag :title, params[:title] %>

  	<%= label_tag :content %>
  	<%= text_field_tag :content %>
  <%= submit_tag "Customize", class: "btn btn-large btn-primary" %>
  <% end %>-->

</div>
</div>

app/views/profiles/show.html.erb
<%= provide(:title, @user.profile.title) %>
<h1><%= @user.profile.title %></h1>

<p><%= @user.profile.content %></p>


app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>


      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
        	<% for message in @user.errors.full_messages %>
          	  <li><%= message %></li>
            <% end %>
          </ul>
		</div>
 	 <% end %>

  	<%= f.label :email %>
  	<%= f.text_field :email %>

  	<%= f.label :password %>
  	<%= f.password_field :password %>

  	<%= f.label :password_confirmation %>
  	<%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>
  </div>
</div>